let jokes = [
    "Why don't scientists trust atoms? Because they make up everything!",
    "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    "What did one ocean say to the other ocean? Nothing, they just waved.",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "Parallel lines have so much in common. It's a shame they'll never meet.",
    "I only know 25 letters of the alphabet. I don't know y.",
    "Why did the math book look sad? Because it had too many problems.",
    "Why don't skeletons fight each other? They don't have the guts.",
    "I used to play piano by ear, but now I use my hands and fingers.",
    "Why don't oysters donate to charity? Because they are shellfish.",
    "How do you organize a space party? You planet!",
    "I asked the librarian if the library had any books on paranoia. She whispered, 'They're right behind you.'",
    "Why don't seagulls fly over the bay? Because then they'd be bagels.",
    "I told my computer I needed a break, and now it won't stop sending me vacation ads.",
    "Why did the bicycle fall over? Because it was two-tired!",
    "I used to be a baker because I kneaded dough.",
    "Why don't scientists trust atoms? Because they make up everything!",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "What did one wall say to the other wall? 'I'll meet you at the corner.'",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "I told my wife she should embrace her mistakes. She gave me a hug.",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
    "What do you call fake spaghetti? An impasta.",
    "Why did the cookie go to the doctor? It was feeling crumbly.",
    "How does a penguin build its house? Igloos it together!",
    "Why did the math book look sad? Because it had too many problems.",
    "Why don't scientists trust atoms? Because they make up everything!",
    "Why did the bicycle fall over? Because it was two-tired!",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "What do you get when you cross a snowman and a vampire? Frostbite.",
    "What do you call a fish wearing a bowtie? Sofishticated.",
    "How does a penguin build its house? Igloos it together!",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
    "What did one hat say to the other? Stay here, I'm going on ahead.",
    "Why don't skeletons fight each other? They don't have the guts.",
    "I only know 25 letters of the alphabet. I don't know y.",
    "Why don't oysters donate to charity? Because they are shellfish.",
    "How does a penguin build its house? Igloos it together!",
    "Why did the bicycle fall over? Because it was two-tired!",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "What do you call a fish wearing a bowtie? Sofishticated.",
    "How does a penguin build its house? Igloos it together!",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
    "What did one hat say to the other? Stay here, I'm going on ahead.",
    "Why don't skeletons fight each other? They don't have the guts.",
    "I only know 25 letters of the alphabet. I don't know y.",
    "Why don't oysters donate to charity? Because they are shellfish.",
    "I used to play piano by ear, but now I use my hands and fingers.",
    "I told my computer I needed a break, and now it won't stop sending me vacation ads.",
    "Why did the bicycle fall over? Because it was two-tired!",
    "I used to be a baker because I kneaded dough.",
    "Why don't scientists trust atoms? Because they make up everything!",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "What did one wall say to the other wall? 'I'll meet you at the corner.'",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "I told my wife she should embrace her mistakes. She gave me a hug.",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
    "What do you call fake spaghetti? An impasta.",
    "Why did the cookie go to the doctor? It was feeling crumbly.",
    "How does a penguin build its house? Igloos it together!",
    "Why did the math book look sad? Because it had too many problems.",
    "Why don't scientists trust atoms? Because they make up everything!",
    "Why did the bicycle fall over? Because it was two-tired!",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "What do you get when you cross a snowman and a vampire? Frostbite.",
    "What do you call a fish wearing a bowtie? Sofishticated.",
    "How does a penguin build its house? Igloos it together!",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
    "What did one hat say to the other? Stay here, I'm going on ahead.",
    "Why don't skeletons fight each other? They don't have the guts.",
    "I only know 25 letters of the alphabet. I don't know y.",
    "Why don't oysters donate to charity? Because they are shellfish.",
    "How does a penguin build its house? Igloos it together!",
    "Why did the bicycle fall over? Because it was two-tired!",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "What do you call a fish wearing a bowtie? Sofishticated.",
    "How does a penguin build its house? Igloos it together!",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
    "What did one hat say to the other? Stay here, I'm going on ahead.",
    "Why don't skeletons fight each other? They don't have the guts.",
    "I only know 25 letters of the alphabet. I don't know y.",
    "Why don't oysters donate to charity? Because they are shellfish.",
    "I used to play piano by ear, but now I use my hands and fingers.",
    "I told my computer I needed a break, and now it won't stop sending me vacation ads.",
    "Why did the bicycle fall over? Because it was two-tired!",
    "I used to be a baker because I kneaded dough.",
    "Why don't scientists trust atoms? Because they make up everything!",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "What did one wall say to the other wall? 'I'll meet you at the corner.'",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "I told my wife she should embrace her mistakes. She gave me a hug.",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
    "What do you call fake spaghetti? An impasta.",
    "Why did the cookie go to the doctor? It was feeling crumbly.",
    "How does a penguin build its house? Igloos it together!",
    "Why did the math book look sad? Because it had too many problems.",
  ];
  
let randjoke = Math.floor(Math.random() * jokes.length);
let randjoke1 = Math.floor(Math.random() * jokes.length);
let randjoke2= Math.floor(Math.random() * jokes.length);

let ranndomjoke = jokes[randjoke]
let ranndomjoke1 = jokes[randjoke1]
let ranndomjoke2 = jokes[randjoke2]

let jokefill = document.getElementsByClassName("joke")

jokefill[0].innerHTML = ranndomjoke
jokefill[1].innerHTML = ranndomjoke1
jokefill[2].innerHTML = ranndomjoke2